# Generated by Django 2.1.5 on 2019-02-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_image', models.ImageField(upload_to='key_images')),
                ('product_name', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=30)),
                ('problem', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product_hp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('image_in_problem', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
